package by.itacademy.news.controller.constants;

public enum ActionType {
	GO_TO_BASE_PAGE,
	GO_TO_NEWS_LIST,
	GO_TO_VIEW_NEWS,
	GO_TO_ADD_NEWS_PAGE,
	GO_TO_REG_PAGE,
	GO_TO_AUTH_PAGE,
	GO_TO_ERROR_PAGE,
	DO_SIGN_IN,
	DO_SIGN_OUT,
	DO_REGISTRATION,
	SAVE_NEWS,
	DELETE_NEWS,
	GO_TO_EDIT_PAGE,
	ADD_NEWS,
	CHANGE_LANG;
}
